%TVDtest

%__________________TVD Corrections___________________________ 

%Vector with mass fluxes 
f_C=[-3,4,3.1,-3.9];

%Vector with nodal values
u_vec=[2.9,2.3,2.8,4.5,3];
v_vec=[0.1,3.8,0.5,3.6,4];

%vector with Gradients for U
grad_u_mat=[grad_u(i,j-1,1,1),grad_u(i,j-1,1,2);...
    grad_u(i-1,j,1,1),grad_u(i-1,j,1,2);...
    grad_u(i,j+1,1,1),grad_u(i,j+1,1,2);...
    grad_u(i+1,j,1,1),grad_u(i+1,j,1,2);...
    grad_u(i,j,1,1),grad_u(i,j,1,2)];

%vector with gradients for V
grad_v_mat=[grad_v(i,j-1,1,1),grad_v(i,j-1,1,2);...
    grad_v(i-1,j,1,1),grad_v(i-1,j,1,2);...
    grad_v(i,j+1,1,1),grad_v(i,j+1,1,2);...
    grad_v(i+1,j,1,1),grad_v(i+1,j,1,2);...
    grad_v(i,j,1,1),grad_v(i,j,1,2)];

%Vector with vectors from P to Neigborhood nodes
r_mat=[VecCentNbNods(i,j,1,1),VecCentNbNods(i,j,1,2);...
    VecCentNbNods(i,j,2,1),VecCentNbNods(i,j,2,2);...
    VecCentNbNods(i,j,3,1),VecCentNbNods(i,j,3,2);...
    VecCentNbNods(i,j,4,1),VecCentNbNods(i,j,4,2)];


[s_dc_total_x,s_dc_total_y] = tvdDefCorr(f_C,u_vec,v_vec,...
    grad_u_mat,grad_v_mat,r_mat);